#!/usr/bin/env python3
"""Download the Carson OFL type library into public/fonts."""

from __future__ import annotations

import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS_DIR = ROOT / "public" / "fonts"
CSS_PATH = ROOT / "public" / "fonts.css"
CDN = "https://cdn.jsdelivr.net/fontsource/fonts"

# Keep in sync with src/lib/fonts.ts
LIBRARY: list[tuple[str, str, list[int]]] = [
    ("Bebas Neue", "bebas-neue", [400]),
    ("Oswald", "oswald", [400, 700]),
    ("Anton", "anton", [400]),
    ("Barlow Condensed", "barlow-condensed", [400, 700, 800]),
    ("Saira Extra Condensed", "saira-extra-condensed", [400, 700, 800]),
    ("Big Shoulders Display", "big-shoulders-display", [400, 700, 900]),
    ("Archivo Black", "archivo-black", [400]),
    ("Staatliches", "staatliches", [400]),
    ("Syne", "syne", [700, 800]),
    ("Anybody", "anybody", [400, 700, 900]),
    ("Archivo", "archivo", [400, 700, 900]),
    ("Barlow", "barlow", [400, 700, 800]),
    ("Chivo", "chivo", [400, 700, 900]),
    ("Instrument Sans", "instrument-sans", [400, 700]),
    ("Instrument Serif", "instrument-serif", [400]),
    ("Fraunces", "fraunces", [400, 700]),
    ("Bodoni Moda", "bodoni-moda", [400, 700, 900]),
    ("Newsreader", "newsreader", [400, 700]),
    ("Zilla Slab", "zilla-slab", [400, 700]),
    ("Special Elite", "special-elite", [400]),
    ("IBM Plex Mono", "ibm-plex-mono", [400, 700]),
]


def download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    request = urllib.request.Request(url, headers={"User-Agent": "carson-font-import"})
    with urllib.request.urlopen(request, timeout=60) as response:
        dest.write_bytes(response.read())


def import_fonts() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    faces: list[str] = [
        "/* Generated by scripts/import-fonts.py — OFL type library for Carson. */",
        "",
    ]
    for family, slug, weights in LIBRARY:
        for weight in weights:
            filename = f"{slug}-{weight}.woff2"
            url = f"{CDN}/{slug}@latest/latin-{weight}-normal.woff2"
            dest = FONTS_DIR / filename
            try:
                download(url, dest)
            except Exception as error:  # noqa: BLE001
                print(f"  skip {family} {weight}: {error}", file=sys.stderr)
                continue
            print(f"  {family} {weight} ({dest.stat().st_size} bytes)")
            faces.append("@font-face {")
            faces.append(f"  font-family: '{family}';")
            faces.append("  font-style: normal;")
            faces.append(f"  font-weight: {weight};")
            faces.append("  font-display: swap;")
            faces.append(f"  src: url('./fonts/{filename}') format('woff2');")
            faces.append("}")
            faces.append("")
    CSS_PATH.write_text("\n".join(faces), encoding="utf-8")
    print(f"Wrote {CSS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(import_fonts())
